export const mockData = [
  {
    id: 1,
    name: "Conferinta despre gaste",
    conferenceType: "Remote",
    location: "Sala Palatului",
    speaker: "John",
    city: "Brasov",
    county: "Brasov",
    country: "USA",
    startDate: "11/11/2025 13:00:00",
    endDate: "20:00:00",
    attendeesNumber: 100
  },
  {
    id: 2,
    name: "C#",
    conferenceType: "Remote",
    location: "Sala Palatului",
    speaker: "Alice",
    city: "Brasov",
    county: "Brasov",
    country: "Canada",
    startDate: "11/11/2025 13:00:00",
    endDate: "11/11/2025 20:00:00",
    attendeesNumber: 5
  },
  {
    id: 3,
    name: "Avioane americane",
    conferenceType: "On Site",
    location: "Sala Palatului",
    speaker: "Bob",
    city: "Brasov",
    county: "Brasov",
    country: "UK",
    startDate: "11/11/2025 13:00:00",
    endDate: "11/11/2025 20:00:00",
    attendeesNumber: 5
  },
  {
    id: 4,
    name: "Alunelu",
    conferenceType: "On Site",
    location: "Sala Palatului",
    speaker: "Bob",
    city: "Brasov",
    county: "Brasov",
    country: "UK",
    startDate: "11/11/2025 13:00:00",
    endDate: "11/11/2025 20:00:00",
    attendeesNumber: 5
  },
  {
    id: 5,
    name: "TedX",
    conferenceType: "On Site",
    location: "Sala Palatului",
    speaker: "Bob",
    city: "Brasov",
    county: "Brasov",
    country: "UK",
    startDate: "11/11/2025 13:00:00",
    endDate: "11/11/2025 20:00:00",
    attendeesNumber: 12
  },
  {
    id: 6,
    name: "Serpi in natura",
    conferenceType: "On Site",
    location: "Sala Palatului",
    speaker: "Bob",
    city: "Brasov",
    county: "Brasov",
    country: "UK",
    startDate: "11/11/2025 13:00:00",
    endDate: "11/11/2025 20:00:00",
    attendeesNumber: 5
  },
  {
    id: 7,
    name: "Arici",
    conferenceType: "On Site",
    location: "Sala Palatului",
    speaker: "Bob",
    city: "Brasov",
    county: "Brasov",
    country: "UK",
    startDate: "11/11/2025 13:00:00",
    endDate: "11/11/2025 20:00:00",
    attendeesNumber: 10
  }
];

// Id = conference.Id,
// ConferenceTypeName = conference.ConferenceType?.Name,
// LocationName = conference.Location?.Name,
// CountryName = conference.Location?.Country?.Name,
// CountyName = conference.Location?.County?.Name,
// CityName = conference.Location?.City?.Name,
// OrganizerEmail = conference.OrganizerEmail,
// CategoryName = conference.Category?.Name,
// StartDate = conference.StartDate,
// EndDate = conference.EndDate,
// Name = conference.Name,
// MainSpeakerName = conference.ConferenceXSpeakers?.FirstOrDefault(x => x.IsMainSpeaker)?.Speaker?.Name,
// AtendeesList = atendeesList
